# Generated by Django 4.2.2 on 2023-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_page_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
