# Generated by Django 4.2.2 on 2023-06-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_page_app", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselslide",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
        ),
    ]
