# Generated by Django 4.2.2 on 2023-06-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_page_app", "0003_carouselslide_description_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselslide",
            name="text_alignment",
            field=models.CharField(
                choices=[
                    ("text-left", "Left"),
                    ("text-center", "Center"),
                    ("text-right", "Right"),
                ],
                default="text-left",
                max_length=11,
            ),
        ),
    ]
