# Generated by Django 4.2.2 on 2023-06-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_page_app", "0004_carouselslide_text_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselslide",
            name="button_link",
            field=models.CharField(default="#", max_length=200),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="button_style",
            field=models.CharField(
                choices=[
                    ("btn-primary", "Primary"),
                    ("btn-secondary", "Secondary"),
                    ("btn-success", "Success"),
                    ("btn-danger", "Danger"),
                    ("btn-warning", "Warning"),
                    ("btn-info", "Info"),
                    ("btn-light", "Light"),
                    ("btn-dark", "Dark"),
                    ("btn-link", "Link"),
                ],
                default="btn-primary",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="button_text",
            field=models.CharField(default="Learn More", max_length=100),
        ),
    ]
